apiVersion: v1
kind: Pod
metadata:
  name: restore-from-${VALKEY_VOLUME_NAME}
spec:
  containers:
  - name: alpine-container
    image: alpine:latest  # Alpine Linux is very lightweight
    command: ["/bin/sh"]  # Start a shell session
    tty: true             # Enable TTY
    stdin: true           # Enable stdin for interactive sessions
    volumeMounts: 
    - mountPath: "/mnt"
      name: "valkeydata"
  restartPolicy: Never
  volumes: 
  - name: "valkeydata"
    persistentVolumeClaim: 
      claimName: "${VALKEY_VOLUME_NAME}"
